{% set name = "jq" %}
{% set version = "1.7.1" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/jqlang/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 478c9ca129fd2e3443fe27314b455e211e0d8c60bc8ff7df703873deeee580c2
  patches:                            # [linux and (x86_64 or s390x)]
    # Disable tests/shtest on linux-64 and linux-s390x
    - 0001-disable-color-tests.patch  # [linux and (x86_64 or s390x)]

build:
  number: 0
  # Skip the Windows support because m2- and m2w64- stuff is deprecated on the defaults channel
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
    - patch # [linux and (x86_64 or s390x)]
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help  # [not win]
    - test -f ${PREFIX}/bin/jq                  # [unix]
    - test -f ${PREFIX}/include/jq.h            # [unix]
    - test -f ${PREFIX}/include/jv.h            # [unix]
    - test -f ${PREFIX}/lib/libjq.a            # [unix]
    - test -f ${PREFIX}/lib/libjq${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libjq.pc  # [unix]

about:
  home: https://jqlang.github.io/jq/
  dev_url: https://github.com/jqlang/jq
  doc_url: https://jqlang.github.io/jq/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A command-line JSON processor.
  description: |
    jq is a lightweight and flexible command-line JSON processor
    akin to sed,awk,grep, and friends for JSON data.
    It's written in portable C and has zero runtime dependencies,
    allowing you to easily slice, filter, map, and transform structured data.

extra:
  recipe-maintainers:
    - jakirkham
    - '0xbe7a'
