{% set name = "jq" %}
{% set version = "1.8.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}lang/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz  # [unix]
  sha256: 2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0  # [unix]
  patches:  # [unix]
    - patches/0001-disable-test-no-color-on-linux-64.patch # [linux and x86_64]

  # Skip the Windows build because m2- and m2w64- stuff is deprecated on the defaults channel, binary repack used instead.
  url: https://github.com/{{ name }}lang/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-win64.exe  # [win]
  sha256: 23cb60a1354eed6bcc8d9b9735e8c7b388cd1fdcb75726b93bc299ef22dd9334  # [win]

build:
  number: 0
  ignore_run_exports:  # [win]
    - vc14_runtime  # [win]

requirements:
  build:
    - patch  # [linux and x86_64]
    - {{ compiler('c') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - make  # [unix]
  host:
    - oniguruma 6.9.*  # [unix]
  run:
    - oniguruma 6.9.*  # [unix]

test:
  commands:
    - jq --help
    - test -f ${PREFIX}/bin/jq  # [unix]
    - test -f ${PREFIX}/include/jq.h  # [unix]
    - test -f ${PREFIX}/include/jv.h  # [unix]
    - test -f ${PREFIX}/lib/libjq.a  # [unix]
    - test -f ${PREFIX}/lib/libjq${SHLIB_EXT}  # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libjq.pc  # [unix]

about:
  home: https://github.com/jqlang/jq
  summary: A command-line JSON processor.
  license: MIT
  license_family: MIT
  license_file: COPYING
  description: |
    jq is a lightweight and flexible command-line JSON processor
    akin to sed,awk,grep, and friends for JSON data.
    It's written in portable C and has zero runtime dependencies,
    allowing you to easily slice, filter, map, and transform structured data.
  dev_url: https://github.com/jqlang/jq
  doc_url: https://jqlang.github.io/jq

extra:
  recipe-maintainers:
    - jakirkham
    - '0xbe7a'
