{% set name = "jq" %}
{% set version = "1.8.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}lang/{{ name }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2be64e7129cecb11d5906290eba10af694fb9e3e7f9fc208a311dc33ca837eb0

build:
  number: 0
  # Skip the Windows support because m2- and m2w64- stuff is deprecated on the defaults channel
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
  host:
    - oniguruma 6.9.*
  run:
    - oniguruma 6.9.*

test:
  commands:
    - jq --help
    - test -f ${PREFIX}/bin/jq
    - test -f ${PREFIX}/include/jq.h
    - test -f ${PREFIX}/include/jv.h
    - test -f ${PREFIX}/lib/libjq.a
    - test -f ${PREFIX}/lib/libjq${SHLIB_EXT}
    - test -f ${PREFIX}/lib/pkgconfig/libjq.pc

about:
  home: https://github.com/jqlang/jq
  summary: A command-line JSON processor.
  license: MIT
  license_family: MIT
  license_file: COPYING
  description: |
    jq is a lightweight and flexible command-line JSON processor
    akin to sed,awk,grep, and friends for JSON data.
    It's written in portable C and has zero runtime dependencies,
    allowing you to easily slice, filter, map, and transform structured data.
  dev_url: https://github.com/jqlang/jq
  doc_url: https://jqlang.github.io/jq

extra:
  recipe-maintainers:
    - jakirkham
    - '0xbe7a'
